In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("House-Price.csv")

In [3]:
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  poor_prop airport  n_hos_beds  n_hot_rooms waterbody  rainfall  \
0      24.7       4.98     YES       5.480      11.1920     River        23   
1      22.2       9.14      NO       7.332      12.1728      Lake        42   
2      22.2       4.03      NO       7.394     101.1200      None        38   
3      21.3       2.94     YES       9.268      11.2672      Lake        45   
4      21.3       5.33      NO       8.824      11.2896      Lake        55   

  bus_ter     parks  Sold  
0     YES  0.049347     0  
1     YES  0.046146     1  
2     YES  0.045764     0  
3     YES  0.047151     0  
4     YES  0.039474     0

In [5]:
df.shape

(506, 19)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   price        506 non-null    float64
 1   resid_area   506 non-null    float64
 2   air_qual     506 non-null    float64
 3   room_num     506 non-null    float64
 4   age          506 non-null    float64
 5   dist1        506 non-null    float64
 6   dist2        506 non-null    float64
 7   dist3        506 non-null    float64
 8   dist4        506 non-null    float64
 9   teachers     506 non-null    float64
 10  poor_prop    506 non-null    float64
 11  airport      506 non-null    object 
 12  n_hos_beds   498 non-null    float64
 13  n_hot_rooms  506 non-null    float64
 14  waterbody    506 non-null    object 
 15  rainfall     506 non-null    int64  
 16  bus_ter      506 non-null    object 
 17  parks        506 non-null    float64
 18  Sold         506 non-null    int64  
dtypes: float

In [7]:
df.n_hos_beds=df.n_hos_beds.fillna(df.n_hos_beds.mean())

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   price        506 non-null    float64
 1   resid_area   506 non-null    float64
 2   air_qual     506 non-null    float64
 3   room_num     506 non-null    float64
 4   age          506 non-null    float64
 5   dist1        506 non-null    float64
 6   dist2        506 non-null    float64
 7   dist3        506 non-null    float64
 8   dist4        506 non-null    float64
 9   teachers     506 non-null    float64
 10  poor_prop    506 non-null    float64
 11  airport      506 non-null    object 
 12  n_hos_beds   506 non-null    float64
 13  n_hot_rooms  506 non-null    float64
 14  waterbody    506 non-null    object 
 15  rainfall     506 non-null    int64  
 16  bus_ter      506 non-null    object 
 17  parks        506 non-null    float64
 18  Sold         506 non-null    int64  
dtypes: float

In [9]:
df=pd.get_dummies(df)

In [11]:
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  ...  rainfall     parks  Sold  airport_NO  airport_YES  \
0      24.7  ...        23  0.049347     0           0            1   
1      22.2  ...        42  0.046146     1           1            0   
2      22.2  ...        38  0.045764     0           1            0   
3      21.3  ...        45  0.047151     0           0            1   
4      21.3  ...        55  0.039474     0           1            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_None  waterbody_River  \
0               0                         0               0                1   
1               1                         0               0                0   
2               0                         0               1                0   
3               1                         0               0                0   
4               1                         0               0                0   

   bus_ter_YES  
0            1  
1            1  
2            1  
3            1  
4            1  

[5 rows x 23 columns]

In [12]:
del df['waterbody_Lake and River']

In [13]:
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  ...  n_hot_rooms  rainfall     parks  Sold  airport_NO  \
0      24.7  ...      11.1920        23  0.049347     0           0   
1      22.2  ...      12.1728        42  0.046146     1           1   
2      22.2  ...     101.1200        38  0.045764     0           1   
3      21.3  ...      11.2672        45  0.047151     0           0   
4      21.3  ...      11.2896        55  0.039474     0           1   

   airport_YES  waterbody_Lake  waterbody_None  waterbody_River  bus_ter_YES  
0            1               0               0                1            1  
1            0               1               0                0            1  
2            0               0               1                0            1  
3            1               1               0                0            1  
4            0               1               0                0            1  

[5 rows x 22 columns]

In [24]:
x=df.loc[:,df.columns!='Sold']

In [15]:
y=df['Sold']

In [16]:
x.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  ...  n_hos_beds  n_hot_rooms  rainfall     parks  airport_NO  \
0      24.7  ...       5.480      11.1920        23  0.049347           0   
1      22.2  ...       7.332      12.1728        42  0.046146           1   
2      22.2  ...       7.394     101.1200        38  0.045764           1   
3      21.3  ...       9.268      11.2672        45  0.047151           0   
4      21.3  ...       8.824      11.2896        55  0.039474           1   

   airport_YES  waterbody_Lake  waterbody_None  waterbody_River  bus_ter_YES  
0            1               0               0                1            1  
1            0               1               0                0            1  
2            0               0               1                0            1  
3            1               1               0                0            1  
4            0               1               0                0            1  

[5 rows x 21 columns]

In [17]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [18]:
from sklearn.linear_model import LogisticRegression

In [25]:
clf_lr=LogisticRegression()
clf_lr.fit(x,y)

C:\Users\sandi\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
import statsmodels.api as sn

In [30]:
x_cons=sn.add_constant(x)

In [31]:
import statsmodels.discrete.discrete_model as sm

In [32]:
logit = sm.Logit(y,x_cons).fit()

Optimization terminated successfully.
         Current function value: 0.549617
         Iterations 11


### Predicting and confusion matrix

In [34]:
clf_lr.predict_proba(x)

array([[1.35505968e-01, 8.64494032e-01],
       [4.12489042e-01, 5.87510958e-01],
       [9.99737784e-01, 2.62216156e-04],
       ...,
       [2.95225559e-01, 7.04774441e-01],
       [2.98963600e-01, 7.01036400e-01],
       [1.80488831e-01, 8.19511169e-01]])

In [35]:
y_pred=clf_lr.predict(x)

In [36]:
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [39]:
y_pred_03=(clf_lr.predict_proba(x)[:,1]>=0.3)

In [44]:
y_pred_03

array([ True,  True, False,  True, False, False,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False, False,

In [42]:
from sklearn.metrics import confusion_matrix

In [43]:
confusion_matrix(y,y_pred)

array([[197,  79],
       [ 79, 151]], dtype=int64)

In [45]:
confusion_matrix(y,y_pred_03)

array([[118, 158],
       [ 17, 213]], dtype=int64)

### Performance matrix

In [46]:
from sklearn.metrics import precision_score,recall_score

In [47]:
precision_score(y,y_pred)

0.6565217391304348

In [48]:
recall_score(y,y_pred)

0.6565217391304348

In [50]:
from sklearn.metrics import roc_auc_score

In [51]:
roc_auc_score(y,y_pred)

0.6851449275362319

### Linear Discriminant Analysis

In [53]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [54]:
clf_lda = LinearDiscriminantAnalysis()

In [56]:
clf_lda.fit(x,y)

LinearDiscriminantAnalysis()

In [57]:
y_pred_lda = clf_lda.predict(x)

In [61]:
y_pred_lda

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,

In [60]:
confusion_matrix(y,y_pred_lda)

array([[201,  75],
       [ 76, 154]], dtype=int64)